// <auto-generated />
using System;
using CargoApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CargoApi.Migrations
{
    [DbContext(typeof(PRIORITY_WWDContext))]
    [Migration("20231224074945_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CargoApi.Models.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Carir_Nme")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("CRIR_NME");

                    b.Property<string>("Id_Img")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ID_IMG");

                    b.Property<string>("Lcns_Plt_Nmbr")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("LCNS_PLT_NMBR");

                    b.Property<string>("Nme")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("NME");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("Rpnt")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("RPNT");

                    b.Property<string>("ShptNmbr")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("SHPT_NMBR");

                    b.Property<int?>("TransferId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("D_TYPE");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ShptNmbr");

                    b.HasIndex("TransferId");

                    b.ToTable("Driver", (string)null);
                });

            modelBuilder.Entity("CargoApi.Models.Fixture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("DUnit")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("LNTH_UNIT");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("HGHT");

                    b.Property<decimal?>("Length")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("LNTH");

                    b.Property<string>("Ptype")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PRDT_TYPE");

                    b.Property<int?>("Qnty")
                        .HasColumnType("int")
                        .HasColumnName("QNTY");

                    b.Property<string>("RcptNmbr")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("RCPT_NMBR");

                    b.Property<string>("ShptNmbr")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("SHPT_NMBR");

                    b.Property<string>("WUnit")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("WGHT_UNIT");

                    b.Property<decimal?>("Wght")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("WGHT");

                    b.Property<decimal?>("Width")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("WDTH");

                    b.HasKey("Id");

                    b.HasIndex("ShptNmbr");

                    b.ToTable("FIXTURE", (string)null);
                });

            modelBuilder.Entity("CargoApi.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CstmRpnt")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CSTM_RPNT");

                    b.Property<string>("Imgs")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("IMGS");

                    b.Property<string>("Locn")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("LOCN");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("NAME");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOTE");

                    b.Property<int?>("Qnty")
                        .HasColumnType("int")
                        .HasColumnName("QNTY");

                    b.Property<string>("Rpnt")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RPNT");

                    b.Property<string>("ShptNmbr")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("SHPT_NMBR");

                    b.Property<string>("Sts")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("STS");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ShptNmbr" }, "UQ__ORDERS__5E9EFC15B8EA01E9")
                        .IsUnique();

                    b.ToTable("ORDERS", (string)null);
                });

            modelBuilder.Entity("CargoApi.Models.Order_Fixture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("DUnit")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("LNTH_UNIT");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("HGHT");

                    b.Property<decimal?>("Length")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("LNTH");

                    b.Property<string>("Ptype")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PRDT_TYPE");

                    b.Property<int?>("Qnty")
                        .HasColumnType("int")
                        .HasColumnName("QNTY");

                    b.Property<string>("RcptNmbr")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("RCPT_NMBR");

                    b.Property<string>("ShptNmbr")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("SHPT_NMBR");

                    b.Property<string>("WUnit")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("WGHT_UNIT");

                    b.Property<decimal?>("Wght")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("WGHT");

                    b.Property<decimal?>("Width")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("WDTH");

                    b.HasKey("Id");

                    b.HasIndex("ShptNmbr");

                    b.ToTable("ORDER_FIXTURE", (string)null);
                });

            modelBuilder.Entity("CargoApi.Models.Order_Receipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("RcptNmbr")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("RCPT_NMBR");

                    b.Property<string>("ShptNmbr")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("SHPT_NMBR");

                    b.HasKey("Id");

                    b.HasIndex("ShptNmbr");

                    b.ToTable("ORDER_RECEIPT", (string)null);
                });

            modelBuilder.Entity("CargoApi.Models.Receipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("RcptNmbr")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("RCPT_NMBR");

                    b.Property<string>("ShptNmbr")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("SHPT_NMBR");

                    b.HasKey("Id");

                    b.HasIndex("ShptNmbr");

                    b.ToTable("RECEIPT", (string)null);
                });

            modelBuilder.Entity("CargoApi.Models.Shipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CstmRpnt")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CSTM_RPNT");

                    b.Property<string>("Imgs")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("IMGS");

                    b.Property<string>("Locn")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("LOCN");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("NAME");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOTE");

                    b.Property<int?>("Qnty")
                        .HasColumnType("int")
                        .HasColumnName("QNTY");

                    b.Property<string>("Rpnt")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RPNT");

                    b.Property<string>("ShptNmbr")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("SHPT_NMBR");

                    b.Property<string>("Sts")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("STS");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ShptNmbr" }, "UQ__SHIPMENT__5E9EFC15B8EA01E9")
                        .IsUnique();

                    b.ToTable("SHIPMENT", (string)null);
                });

            modelBuilder.Entity("CargoApi.Models.Transfer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CstmRpnt")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CSTM_RPNT");

                    b.Property<string>("Imgs")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("IMGS");

                    b.Property<string>("Locn")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("LOCN");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("NAME");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOTE");

                    b.Property<int?>("Qnty")
                        .HasColumnType("int")
                        .HasColumnName("QNTY");

                    b.Property<string>("Rpnt")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RPNT");

                    b.Property<string>("ShptNmbr")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("SHPT_NMBR");

                    b.Property<string>("Sts")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("STS");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ShptNmbr" }, "UQ__TRANSFER__5E9EFC15B8EA01E9")
                        .IsUnique();

                    b.ToTable("TRANSFER", (string)null);
                });

            modelBuilder.Entity("CargoApi.Models.Transfer_Fixture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("DUnit")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("LNTH_UNIT");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("HGHT");

                    b.Property<decimal?>("Length")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("LNTH");

                    b.Property<string>("Ptype")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PRDT_TYPE");

                    b.Property<int?>("Qnty")
                        .HasColumnType("int")
                        .HasColumnName("QNTY");

                    b.Property<string>("RcptNmbr")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("RCPT_NMBR");

                    b.Property<string>("ShptNmbr")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("SHPT_NMBR");

                    b.Property<string>("WUnit")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("WGHT_UNIT");

                    b.Property<decimal?>("Wght")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("WGHT");

                    b.Property<decimal?>("Width")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("WDTH");

                    b.HasKey("Id");

                    b.HasIndex("ShptNmbr");

                    b.ToTable("TRANSFER_FIXTURE", (string)null);
                });

            modelBuilder.Entity("CargoApi.Models.Transfer_Receipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("RcptNmbr")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("RCPT_NMBR");

                    b.Property<string>("ShptNmbr")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("SHPT_NMBR");

                    b.HasKey("Id");

                    b.HasIndex("ShptNmbr");

                    b.ToTable("TRANSFER_RECEIPT", (string)null);
                });

            modelBuilder.Entity("CargoApi.Models.Driver", b =>
                {
                    b.HasOne("CargoApi.Models.Order", null)
                        .WithMany("Drivers")
                        .HasForeignKey("OrderId");

                    b.HasOne("CargoApi.Models.Shipment", "ShptNmbrNavigationDriver")
                        .WithMany("Drivers")
                        .HasForeignKey("ShptNmbr")
                        .HasPrincipalKey("ShptNmbr")
                        .HasConstraintName("FK__Driver__SHPT_NMB__09A971A2");

                    b.HasOne("CargoApi.Models.Transfer", null)
                        .WithMany("Drivers")
                        .HasForeignKey("TransferId");

                    b.Navigation("ShptNmbrNavigationDriver");
                });

            modelBuilder.Entity("CargoApi.Models.Fixture", b =>
                {
                    b.HasOne("CargoApi.Models.Shipment", "ShptNmbrNavigationFix")
                        .WithMany("Fixtures")
                        .HasForeignKey("ShptNmbr")
                        .HasPrincipalKey("ShptNmbr")
                        .HasConstraintName("FK__FIXTURE__SHPT_NM__3A34245698");

                    b.Navigation("ShptNmbrNavigationFix");
                });

            modelBuilder.Entity("CargoApi.Models.Order", b =>
                {
                    b.OwnsMany("CargoApi.Models.DimensionArrayItem_Order", "DimensionCollection", b1 =>
                        {
                            b1.Property<int>("OrderId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"), 1L, 1);

                            b1.Property<string>("DUnit")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<decimal>("Height")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("Lngth")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("Ptype")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int?>("Qnty")
                                .HasColumnType("int");

                            b1.Property<string>("RcptNmbr")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ShptNmbr")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<decimal>("Width")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("OrderId", "Id");

                            b1.ToTable("DimensionArrayItem_Order");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.OwnsMany("CargoApi.Models.RcptNumbers_Order", "RcptNmbr", b1 =>
                        {
                            b1.Property<int>("OrderId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"), 1L, 1);

                            b1.Property<string>("RcptNmbr")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("OrderId", "Id");

                            b1.ToTable("RcptNumbers_Order");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.OwnsMany("CargoApi.Models.WeightArrayItem_Order", "WeightCollection", b1 =>
                        {
                            b1.Property<int>("OrderId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"), 1L, 1);

                            b1.Property<string>("Ptype")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int?>("Qnty")
                                .HasColumnType("int");

                            b1.Property<string>("RcptNmbr")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ShptNmbr")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("WUnit")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<decimal>("Wght")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("OrderId", "Id");

                            b1.ToTable("WeightArrayItem_Order");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.Navigation("DimensionCollection");

                    b.Navigation("RcptNmbr");

                    b.Navigation("WeightCollection");
                });

            modelBuilder.Entity("CargoApi.Models.Order_Fixture", b =>
                {
                    b.HasOne("CargoApi.Models.Order", "ShptNmbrNavigationOrderFix")
                        .WithMany("Order_Fixtures")
                        .HasForeignKey("ShptNmbr")
                        .HasPrincipalKey("ShptNmbr")
                        .HasConstraintName("FK__ORDER_FIXTURE__SHPT_NM__3A34245698");

                    b.Navigation("ShptNmbrNavigationOrderFix");
                });

            modelBuilder.Entity("CargoApi.Models.Order_Receipt", b =>
                {
                    b.HasOne("CargoApi.Models.Order", "ShptNmbrNavigationOrder")
                        .WithMany("Order_Receipts")
                        .HasForeignKey("ShptNmbr")
                        .HasPrincipalKey("ShptNmbr")
                        .HasConstraintName("FK__ORDER_RECEIPT__SHPT_NM__3A342422");

                    b.Navigation("ShptNmbrNavigationOrder");
                });

            modelBuilder.Entity("CargoApi.Models.Receipt", b =>
                {
                    b.HasOne("CargoApi.Models.Shipment", "ShptNmbrNavigation")
                        .WithMany("Receipts")
                        .HasForeignKey("ShptNmbr")
                        .HasPrincipalKey("ShptNmbr")
                        .HasConstraintName("FK__RECEIPT__SHPT_NM__3A81B327");

                    b.Navigation("ShptNmbrNavigation");
                });

            modelBuilder.Entity("CargoApi.Models.Shipment", b =>
                {
                    b.OwnsMany("CargoApi.Models.DimensionArrayItem", "DimensionCollection", b1 =>
                        {
                            b1.Property<int>("ShipmentId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"), 1L, 1);

                            b1.Property<string>("DUnit")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<decimal>("Height")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("Lngth")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("Ptype")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int?>("Qnty")
                                .HasColumnType("int");

                            b1.Property<string>("RcptNmbr")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ShptNmbr")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<decimal>("Width")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("ShipmentId", "Id");

                            b1.ToTable("DimensionArrayItem");

                            b1.WithOwner()
                                .HasForeignKey("ShipmentId");
                        });

                    b.OwnsMany("CargoApi.Models.RcptNumbers", "RcptNmbr", b1 =>
                        {
                            b1.Property<int>("ShipmentId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"), 1L, 1);

                            b1.Property<string>("RcptNmbr")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ShipmentId", "Id");

                            b1.ToTable("RcptNumbers");

                            b1.WithOwner()
                                .HasForeignKey("ShipmentId");
                        });

                    b.OwnsMany("CargoApi.Models.WeightArrayItem", "WeightCollection", b1 =>
                        {
                            b1.Property<int>("ShipmentId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"), 1L, 1);

                            b1.Property<string>("Ptype")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int?>("Qnty")
                                .HasColumnType("int");

                            b1.Property<string>("RcptNmbr")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ShptNmbr")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("WUnit")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<decimal>("Wght")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("ShipmentId", "Id");

                            b1.ToTable("WeightArrayItem");

                            b1.WithOwner()
                                .HasForeignKey("ShipmentId");
                        });

                    b.Navigation("DimensionCollection");

                    b.Navigation("RcptNmbr");

                    b.Navigation("WeightCollection");
                });

            modelBuilder.Entity("CargoApi.Models.Transfer", b =>
                {
                    b.OwnsMany("CargoApi.Models.DimensionArrayItem_Transfer", "DimensionCollection", b1 =>
                        {
                            b1.Property<int>("TransferId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"), 1L, 1);

                            b1.Property<string>("DUnit")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<decimal>("Height")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("Lngth")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("Ptype")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int?>("Qnty")
                                .HasColumnType("int");

                            b1.Property<string>("RcptNmbr")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ShptNmbr")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<decimal>("Width")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("TransferId", "Id");

                            b1.ToTable("DimensionArrayItem_Transfer");

                            b1.WithOwner()
                                .HasForeignKey("TransferId");
                        });

                    b.OwnsMany("CargoApi.Models.RcptNumbers_Transfer", "RcptNmbr", b1 =>
                        {
                            b1.Property<int>("TransferId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"), 1L, 1);

                            b1.Property<string>("RcptNmbr")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("TransferId", "Id");

                            b1.ToTable("RcptNumbers_Transfer");

                            b1.WithOwner()
                                .HasForeignKey("TransferId");
                        });

                    b.OwnsMany("CargoApi.Models.WeightArrayItem_Transfer", "WeightCollection", b1 =>
                        {
                            b1.Property<int>("TransferId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"), 1L, 1);

                            b1.Property<string>("Ptype")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int?>("Qnty")
                                .HasColumnType("int");

                            b1.Property<string>("RcptNmbr")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ShptNmbr")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("WUnit")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<decimal>("Wght")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("TransferId", "Id");

                            b1.ToTable("WeightArrayItem_Transfer");

                            b1.WithOwner()
                                .HasForeignKey("TransferId");
                        });

                    b.Navigation("DimensionCollection");

                    b.Navigation("RcptNmbr");

                    b.Navigation("WeightCollection");
                });

            modelBuilder.Entity("CargoApi.Models.Transfer_Fixture", b =>
                {
                    b.HasOne("CargoApi.Models.Transfer", "ShptNmbrNavigationTransferFix")
                        .WithMany("Transfer_Fixtures")
                        .HasForeignKey("ShptNmbr")
                        .HasPrincipalKey("ShptNmbr")
                        .HasConstraintName("FK__TRANSFER_FIXTURE__SHPT_NM__3A34245698");

                    b.Navigation("ShptNmbrNavigationTransferFix");
                });

            modelBuilder.Entity("CargoApi.Models.Transfer_Receipt", b =>
                {
                    b.HasOne("CargoApi.Models.Transfer", "ShptNmbrNavigationTransfer")
                        .WithMany("Transfer_Receipts")
                        .HasForeignKey("ShptNmbr")
                        .HasPrincipalKey("ShptNmbr")
                        .HasConstraintName("FK__TRANSFER_RECEIPT__SHPT_NM__3A81B327");

                    b.Navigation("ShptNmbrNavigationTransfer");
                });

            modelBuilder.Entity("CargoApi.Models.Order", b =>
                {
                    b.Navigation("Drivers");

                    b.Navigation("Order_Fixtures");

                    b.Navigation("Order_Receipts");
                });

            modelBuilder.Entity("CargoApi.Models.Shipment", b =>
                {
                    b.Navigation("Drivers");

                    b.Navigation("Fixtures");

                    b.Navigation("Receipts");
                });

            modelBuilder.Entity("CargoApi.Models.Transfer", b =>
                {
                    b.Navigation("Drivers");

                    b.Navigation("Transfer_Fixtures");

                    b.Navigation("Transfer_Receipts");
                });
#pragma warning restore 612, 618
        }
    }
}
