// <auto-generated />
using System;
using CargoApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CargoApi.Migrations
{
    [DbContext(typeof(PRIORITY_WWDContext))]
    partial class PRIORITY_WWDContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CargoApi.Models.Receipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("RcptNmbr")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("RCPT_NMBR");

                    b.Property<string>("ShptNmbr")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("SHPT_NMBR");

                    b.HasKey("Id");

                    b.HasIndex("ShptNmbr");

                    b.ToTable("RECEIPT", (string)null);
                });

            modelBuilder.Entity("CargoApi.Models.Shipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CstmRpnt")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CSTM_RPNT");

                    b.Property<decimal?>("Dmnsn")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("DMNSN");

                    b.Property<string>("Imgs")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("IMGS");

                    b.Property<string>("Locn")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("LOCN");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("NAME");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOTE");

                    b.Property<int?>("Qnty")
                        .HasColumnType("int")
                        .HasColumnName("QNTY");

                    b.Property<string>("Rpnt")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RPNT");

                    b.Property<string>("ShptNmbr")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("SHPT_NMBR");

                    b.Property<decimal?>("Wght")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("WGHT");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ShptNmbr" }, "UQ__SHIPMENT__5E9EFC15B8EA01E9")
                        .IsUnique();

                    b.ToTable("SHIPMENT", (string)null);
                });

            modelBuilder.Entity("CargoApi.Models.Receipt", b =>
                {
                    b.HasOne("CargoApi.Models.Shipment", "ShptNmbrNavigation")
                        .WithMany("Receipts")
                        .HasForeignKey("ShptNmbr")
                        .HasPrincipalKey("ShptNmbr")
                        .HasConstraintName("FK__RECEIPT__SHPT_NM__3A81B327");

                    b.Navigation("ShptNmbrNavigation");
                });

            modelBuilder.Entity("CargoApi.Models.Shipment", b =>
                {
                    b.Navigation("Receipts");
                });
#pragma warning restore 612, 618
        }
    }
}
